[pytest]
minversion = 7.0
addopts = -ra -q --strict-markers --tb=long --log-cli-level=DEBUG --log-cli-format="%(asctime)s [%(levelname)s] %(name)s: %(message)s" --log-cli-date-format="%Y-%m-%d %H:%M:%S" --capture=no
testpaths =
    tests/unit
    tests/integration
    tests/e2e
asyncio_mode = auto